### ISSUE TITLE
Figure out the matrix generation

### ISSUE THREAD

**Issue by altendky** [altendky/romp#2]
@vtbassmatt, here's a ticket for general conversation if needed.  I'll try to dig through the differences between my code and your example.
https://github.com/altendky/romp/commit/6e553f4b4ba223b38609225861446076f50739a0#commitcomment-32967610

**Comment by altendky** [comment]
@vtbassmatt, here we go.  :]  The matrixing works.  I had a JSON list at the top of the matrix, not a JSON dict.  I wasn't sure if it was supposed to be JSON or YAML or...  I'll go use the JSON library instead of hand coding that stuff.

https://dev.azure.com/altendky/romp/_build/results?buildId=491

Now on to the other errors I can maybe fix.

**Comment by vtbassmatt** [comment]
Sweet! I got as far as forking your repo and running a build, but hadn't had a chance to get any deeper.

**Comment by altendky** [comment]
I suppose https://github.com/altendky/romp/pull/1 really is the place to talk...  too bad I forgot about it.
